# Generated by Django 2.2.16 on 2022-11-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientsrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_recipe",
                to="food.Ingredients",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="food.Recipes",
            ),
        ),
    ]
