# Generated by Django 3.2.16 on 2022-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_auto_20221119_1505"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredients",
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
    ]
