# Generated by Django 2.2.16 on 2022-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_ingredients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='MEDIA_URL'),
        ),
    ]
