# Generated by Django 2.2.16 on 2022-11-27 09:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_auto_20221123_2324"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientsrecipe",
            options={
                "verbose_name": "Ингредиент для рецепта",
                "verbose_name_plural": "Ингредиенты для рецептов",
            },
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="measurement_unit",
            field=models.CharField(
                max_length=200, verbose_name="Ед. измерения"
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="ingredientsrecipe",
            name="amount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Должен быть хотя бы один ингредиент!"
                    )
                ],
                verbose_name="Кол-во",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_recipe",
                to="food.Ingredients",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="food.Recipes",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="cooking_time",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время приготовления должно быть не менее 1"
                    )
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="ingredients",
            field=models.ManyToManyField(
                through="food.IngredientsRecipe",
                to="food.Ingredients",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="tags",
            field=models.ManyToManyField(to="food.Tag", verbose_name="Теги"),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="text",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=7, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AddConstraint(
            model_name="recipes",
            constraint=models.UniqueConstraint(
                fields=("author", "name"), name="author_recipe_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_user_recipe"
            ),
        ),
    ]
