# Generated by Django 2.2.16 on 2022-11-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0008_auto_20221127_1226"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shoppingcart",
            name="unique_user_recipe",
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"),
                name="unique_user_recipe_shopping_cart",
            ),
        ),
    ]
